#!/usr/bin/env sh

SESSION=1914

echo "Creating a new tmux session \"$SESSION\"..."
echo " "

sleep 2

if tmux has-session -t "$SESSION" 2>/dev/null; then
	echo "Session \"$SESSION\" already exists, attaching..."
	sleep 2

	tmux a -t "$SESSION"
	exit 0
fi

tmux new-session -d -s "$SESSION" -n main
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux send-keys -t "$SESSION:1" "~/.scripts/rss-feed.sh" C-m
tmux new-window -t "$SESSION:2" -n ranger
tmux send-keys -t "$SESSION:2" "ranger" C-m
tmux new-window -t "$SESSION:3" -n ai
tmux send-keys -t "$SESSION:3" "gemini" C-m
tmux new-window -t "$SESSION:4" -n obsidian
tmux send-keys -t "$SESSION:4" "obsdn" C-m
tmux send-keys -t "$SESSION:4" "nvim ." C-m
tmux new-window -t "$SESSION:5" -n stats
tmux send-keys -t "$SESSION:5" "btop" C-m

tmux a -t "$SESSION":1


echo "attached to the tmux session $SESSION."
echo " "
