#!/usr/bin/env sh

name="$USER"

echo "Goood Morning, $name!"
echo "Today is $(date +%A), $(date +%B) $(date +%d), $(date +%Y)."
echo " "
echo -n "Enter name of the tmux session: " 
read SESSION
echo " "

echo "Creating a new tmux session \"$SESSION\"..."

sleep 2

if tmux has-session -t "$SESSION" 2>/dev/null; then
	echo "Session \"$SESSION\" already exists, attaching..."
	sleep 2

	tmux a -t "$SESSION"
	exit 0
fi

tmux new-session -d -s "$SESSION" -n main
tmux send-keys -t "$SESSION:1" "clear" C-m
tmux new-window -t "$SESSION:2" -n ranger
tmux send-keys -t "$SESSION:2" "ranger" C-m
tmux new-window -t "$SESSION:3" -n ai
tmux send-keys -t "$SESSION:3" "gemini" C-m

tmux a -t "$SESSION":1



echo "attached to the tmux session $SESSION."
