set -g status-justify left
setw -g mode-keys vi
set-option -g status-style bg=default,fg=#a0028c
set -gq allow-passthrough on
set -g visual-activity off

# Start window and pane numbers at 1
set -g base-index 1
setw -g pane-base-index 1

# Left: user, session, branch or "no-repo"
set -g status-left '#[default][ #(whoami) ] #[default][ #{session_name} ] #[default][ #(cd "#{pane_current_path}" 2>/dev/null && git rev-parse --is-inside-work-tree >/dev/null 2>&1 && git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "no-repo") ] '
set -g status-left-length 100

# Right: battery (color by condition), time, date
set -g status-right '#[fg=yellow][ #(nmcli -t -f active,ssid dev wifi | grep "^yes" | cut -d: -f2) ]#[default] \
#( \
  perc=$(upower -i $(upower -e | grep BAT) | awk "/percentage/ {gsub(/%/, \"\", \$2); print \$2}"); \
  state=$(upower -i $(upower -e | grep BAT) | awk "/state/ {print \$2}"); \
  if [ "$perc" -eq 100 ]; then \
    echo "#[fg=blue][ ${perc}% ]#[default]"; \
  elif [ "$state" = "charging" ]; then \
    echo "#[fg=green][ ${perc}% ]#[default]"; \
  elif [ "$perc" -lt 20 ]; then \
    echo "#[fg=red][ ${perc}% ]#[default]"; \
  else \
    echo "#[default][ ${perc}% ]"; \
  fi) \
#[default][ #(date +"%H:%Mh") ] \
[ #(date +%-d$(date +%e | awk "{d=\$1+0; print (d==1||d==21||d==31)?\"st\":(d==2||d==22)?\"nd\":(d==3||d==23)?\"rd\":\"th\"")\ %B\ %Y) ]'
set -g status-right-length 100
